sudo: required
language:
  - cpp
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "HrJ3XcDdblwRTIgvCD932Dpvc9+3jO/G8YnoYPCf3USz5z3HpyZ18eAo8rckdrA5aGKCWzOr1RkjinT7Y6KVOIttqi4Z9cgThusMKkjyZQGW+xXByRYZeb5b/QNNC7v/mdGsnQuIjYvlwrL7QmSnlU0iJ3QX1yQOQc/nY/hMAcD5H6+6VAu/ZY2pq1zrs7tPr2g/2QpdoCWb/9x2Egefw5S3IWa5ZUlIth/QMXKRDw7jmWZxzvX5ScMl6JdnnyZHDchVhtozvhDUGlXSUYp96qG2JemDJT05TW8h6Vju3dYMkjFV6Xvno0FLINOFawZ9aA817/hvWPpmZOnV8+DDJtrnMcW9eByvTGo3Kl6M+Yt1B3AAEnRLxijZYuctDG7pxcgb0WbI60/QBN4Lt/AxH14cJKgosiytCKXJAovCfNDhYhGbHaNT/tvPFSvP22zwDshYwQO9tV3bWEr0PEtcztwjgbTSi2jXXzatvjAcgRPujf1dHOl4Xu5FkebKLFRDNYn0KjHao3+cjwGsAepjKnvpJm5zcVMpXkcbtKYsJ3l2YNCbaUCoiO8mSEi1I4BP4CjdxAgZ0x+OdtdRry6l86yg53nP8j5ooUyXp9IlkMDdTczINBBX1ShoDmcEll38ufCsuY2G45ufJZbPOLulGsFMxQGKV/ZWfQ5OVCT+rKg="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo add-apt-repository ppa:george-edison55/precise-backports -y
      - sudo apt-get -qq update
      - sudo ./install-ubuntu.sh
addons:
  coverity_scan:
    project:
      name: "avrabe/CarND-Unscented-Kalman-Filter-Project"
      description: "Build submitted via Travis CI"
    notification_email: ralf_beier@me.com
    build_command_prepend: "mkdir -p build && cd build && cmake .. && make clean "
    build_command:   make
    branch_pattern: coverity_scan

script:
  #- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  #- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  #- export CC=/usr/bin/gcc-6
  #- export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir -p build
  - cd build
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then cmake .. -G "Unix Makefiles" ; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi